server:
  port: 18090
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
  zipkin:
    base-url: http://127.0.0.1:9411
    sender:
      type: web
    discovery-client-enabled: true
  sleuth:
    sampler:
      probability: 1
  redis:
    host: 192.168.184.128
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.184.128:3306/guli_cart
    username: root
    password: 123456
  task:
    execution:
      thread-name-prefix: cart-task-
      pool:
        core-size: 100
        max-size: 500
        queue-capacity: 1000
        keep-alive: 60s
        allow-core-thread-timeout: false
      shutdown:
        await-termination: true
        await-termination-period: 60
  rabbitmq:
    host: 192.168.184.128
    virtual-host: /admin
    username: admin
    password: 123456
    listener:
      simple:
        prefetch: 1
        concurrency: 3
        acknowledge-mode: manual
feign:
  sentinel:
    enabled: true
jwt:
  pubKeyPath: E:\atguigu\java0821\stu\GULISHOPPING\gamll-0821\rsa\rsa.pub
  cookieName: GMALL-TOKEN
  userKey: userKey
  expire: 8640000
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
